## Fake News Classifier Using LSTM

Dataset: https://www.kaggle.com/c/fake-news/data#

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/train (1).csv')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [ ]:
df.shape

(20800, 5)

In [ ]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [ ]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [ ]:
###Drop Nan Values
df=df.dropna()


In [ ]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [ ]:
## Get the Independent Features

X=df.drop('label',axis=1)

In [ ]:
## Get the Dependent features
y=df['label']

In [ ]:
X.shape

(18285, 4)

In [ ]:
y.shape

(18285,)

In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.9.2'

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
### Vocabulary size
voc_size=5000

### Onehot Representation

In [ ]:
messages=X.copy()

In [ ]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [ ]:
messages

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [ ]:
messages.reset_index(inplace=True)

In [ ]:
messages

index     id                                              title  \
0          0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2      2                  Why the Truth Might Get You Fired   
3          3      3  15 Civilians Killed In Single US Airstrike Hav...   
4          4      4  Iranian woman jailed for fictional unpublished...   
...      ...    ...                                                ...   
18280  20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
18281  20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
18282  20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
18283  20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
18284  20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
18280                              Jerome Hudson   
18281                           Benjamin Hoffman   
18282  Michael J. de la Merced and Rachel Abrams   
18283                                Alex Ansary   
18284                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
18280  Rapper T. I. unloaded on black celebrities who...  
18281  When the Green Bay Packers lost to the Washing...  
18282  The Macy’s of today grew from the union of sev...  
18283  NATO, Russia To Hold Parallel Exercises In Bal...  
18284    David Swanson is an author, activist, journa...  

[18285 rows x 5 columns]

In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [ ]:
# nltk.download('wordnet')
# nltk.download('omw-1.4')
# from nltk.stem import WordNetLemmatizer
# lt = WordNetLemmatizer()
# corpus1 = []
# for i in range(0, len(messages)):
#     review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
#     review = review.lower()
#     review = review.split()
    
#     review = [lt.lemmatize(word) for word in review if not word in stopwords.words('english')]
#     review = ' '.join(review)
#     corpus1.append(review)

In [ ]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [ ]:
corpus1[1] #lemmatized one 

In [ ]:
corpus[1] #stemming one

'flynn hillari clinton big woman campu breitbart'

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[1424, 1553, 3606, 3160, 1781, 4107, 1045, 4215, 3942, 1417],
 [2191, 1034, 1002, 415, 4820, 2601, 1404],
 [2741, 2414, 1799, 2745],
 [2941, 3181, 1307, 4917, 4486, 1455],
 [3484, 4820, 4429, 16, 3548, 640, 4820, 824, 4984, 4634],
 [4421,
  2543,
  792,
  4906,
  3563,
  3720,
  907,
  1459,
  4889,
  1091,
  2736,
  3619,
  1708,
  592,
  1404],
 [4164, 4556, 4787, 1628, 1379, 1341, 3283, 1708, 3622, 2542, 2810],
 [488, 4224, 3200, 4858, 1996, 1055, 3720, 2028, 3622, 2542, 2810],
 [583, 931, 4375, 10, 2005, 1584, 211, 1190, 3720, 3804],
 [535, 4771, 162, 689, 997, 3776, 2927, 614],
 [42, 3742, 4364, 3220, 4307, 3823, 1653, 59, 2234, 1847, 4587],
 [4917, 4434, 1781, 1584, 3720, 1996],
 [343, 3661, 1161, 84, 3224, 1231, 1523, 4652, 2194],
 [771, 1684, 728, 1681, 1610, 1338, 2271, 3622, 2542, 2810],
 [1081, 3965, 3185, 3455, 998, 3622, 2542, 2810],
 [4244, 4048, 186, 139, 4532, 58, 2847, 4419, 1043, 3217],
 [2840, 471, 1034],
 [2087, 1491, 342, 2915, 3720, 1239, 2780, 1404],
 [3793, 476

In [ ]:
onehot_repr1=[one_hot(words,voc_size)for words in corpus1] 
onehot_repr1

In [ ]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [ ]:
corpus1[1]

'flynn hillary clinton big woman campus breitbart'

In [ ]:
onehot_repr[1]

[4050, 1583, 3982, 3310, 2806, 2276, 4226]

In [ ]:
onehot_repr1[1]

[4050, 743, 3982, 3310, 2806, 575, 4226]

### Embedding Representation

In [ ]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[1424 1553 3606 ...    0    0    0]
 [2191 1034 1002 ...    0    0    0]
 [2741 2414 1799 ...    0    0    0]
 ...
 [1444 1653 2213 ...    0    0    0]
 [4173 1996 1700 ...    0    0    0]
 [2638 4738  591 ...    0    0    0]]


In [ ]:
sent_length=20
embedded_docs1=pad_sequences(onehot_repr1,padding='post',maxlen=sent_length)
print(embedded_docs1)

[[ 385 1589 4473 ...    0    0    0]
 [4050  743 3982 ...    0    0    0]
 [3109 2268  499 ...    0    0    0]
 ...
 [2519 1713  198 ...    0    0    0]
 [1465 1087 2589 ...    0    0    0]
 [3345  783  581 ...    0    0    0]]


In [ ]:
embedded_docs[1]

array([2191, 1034, 1002,  415, 4820, 2601, 1404,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [ ]:
embedded_docs1[1]

array([4050,  743, 3982, 3310, 2806,  575, 4226,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [ ]:
embedded_docs[0]

array([4485, 1589, 4203, 2284,  505, 4483,    9, 1415, 3864,  838,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [ ]:
embedded_docs1[0]

array([ 385, 1589, 4473, 2284,  505, 4483,    9, 1415, 3864, 2400,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [ ]:
## Creating model
embedding_vector_features=40 ##features representation
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
len(embedded_docs),y.shape

(18285, (18285,))

In [ ]:
len(embedded_docs1),y.shape

(18285, (18285,))

In [ ]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [ ]:
df2 = pd.read_csv("/content/drive/MyDrive/test (1).csv")
df3 = pd.read_csv("/content/drive/MyDrive/submit.csv")

In [ ]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(X_test)):
    review = re.sub('[^a-zA-Z]', ' ', X_test['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

TypeError: ignored

In [ ]:
df2.head()

id                                              title  \
0  20800  Specter of Trump Loosens Tongues, if Not Purse...   
1  20801  Russian warships ready to strike terrorists ne...   
2  20802  #NoDAPL: Native American Leaders Vow to Stay A...   
3  20803  Tim Tebow Will Attempt Another Comeback, This ...   
4  20804                    Keiser Report: Meme Wars (E995)   

                    author                                               text  
0         David Streitfeld  PALO ALTO, Calif.  —   After years of scorning...  
1                      NaN  Russian warships ready to strike terrorists ne...  
2            Common Dreams  Videos #NoDAPL: Native American Leaders Vow to...  
3            Daniel Victor  If at first you don’t succeed, try a different...  
4  Truth Broadcast Network  42 mins ago 1 Views 0 Comments 0 Likes 'For th...

In [ ]:
df3.head()

id  label
0  20800      0
1  20801      1
2  20802      0
3  20803      1
4  20804      1

In [ ]:
X_test = df2
Y_test = df3['label']

In [ ]:
import numpy as np
X_final1=np.array(embedded_docs1)
y_final1=np.array(y)

In [ ]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [ ]:
from sklearn.model_selection import train_test_split
X_train1, X_test1, y_train1, y_test1 = train_test_split(X_final1, y_final1, test_size=0.33, random_state=42)

### Model Training

In [ ]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 9s 10ms/step - loss: 0.3187 - accuracy: 0.8452 - val_loss: 0.1940 - val_accuracy: 0.9167
Epoch 2/10
192/192 [==============================] - 1s 7ms/step - loss: 0.1289 - accuracy: 0.9506 - val_loss: 0.1941 - val_accuracy: 0.9200
Epoch 3/10
192/192 [==============================] - 1s 7ms/step - loss: 0.0837 - accuracy: 0.9703 - val_loss: 0.2183 - val_accuracy: 0.9200
Epoch 4/10
192/192 [==============================] - 1s 7ms/step - loss: 0.0529 - accuracy: 0.9838 - val_loss: 0.2570 - val_accuracy: 0.9173
Epoch 5/10
192/192 [==============================] - 1s 7ms/step - loss: 0.0340 - accuracy: 0.9897 - val_loss: 0.3582 - val_accuracy: 0.9125
Epoch 6/10
192/192 [==============================] - 1s 7ms/step - loss: 0.0243 - accuracy: 0.9927 - val_loss: 0.5194 - val_accuracy: 0.8918
Epoch 7/10
192/192 [==============================] - 1s 7ms/step - loss: 0.0253 - accuracy: 0.9924 - val_loss: 0.4187 - val_accuracy: 0.9090
Epoch

In [ ]:
### Finally Training
model.fit(X_train1,y_train1,validation_data=(X_test1,y_test1),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 1s 7ms/step - loss: 0.0492 - accuracy: 0.9830 - val_loss: 0.3634 - val_accuracy: 0.9059
Epoch 2/10
192/192 [==============================] - 1s 7ms/step - loss: 0.0108 - accuracy: 0.9972 - val_loss: 0.4961 - val_accuracy: 0.9057
Epoch 3/10
192/192 [==============================] - 1s 8ms/step - loss: 0.0056 - accuracy: 0.9984 - val_loss: 0.5769 - val_accuracy: 0.9057
Epoch 4/10
192/192 [==============================] - 1s 7ms/step - loss: 0.0027 - accuracy: 0.9996 - val_loss: 0.6220 - val_accuracy: 0.9065
Epoch 5/10
192/192 [==============================] - 1s 7ms/step - loss: 0.0020 - accuracy: 0.9998 - val_loss: 0.6134 - val_accuracy: 0.9052
Epoch 6/10
192/192 [==============================] - 1s 7ms/step - loss: 0.0019 - accuracy: 0.9998 - val_loss: 0.6978 - val_accuracy: 0.9060
Epoch 7/10
192/192 [==============================] - 1s 7ms/step - loss: 0.0018 - accuracy: 0.9998 - val_loss: 0.6721 - val_accuracy: 0.9034
Epoch 

### Adding Dropout 

In [ ]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

### Performance Metrics And Accuracy

In [ ]:
y_pred=model.predict(X_test)

189/189 [==============================] - 1s 2ms/step


In [ ]:
y_pred=np.where(y_pred > 0.6, 1,0) ##AUC ROC Curve

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_pred,y_test)

array([[3107,  226],
       [ 312, 2390]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)

0.9108533554266777

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.93      0.91      0.92      3419
           1       0.88      0.91      0.90      2616

    accuracy                           0.91      6035
   macro avg       0.91      0.91      0.91      6035
weighted avg       0.91      0.91      0.91      6035

